### ISSUE TITLE
put_object 不支持 cache_control

### ISSUE THREAD

**Issue by raecoo** [aliyun/aliyun-oss-ruby-sdk#16]
官方文档的描述中 Put Object 是支持 Cache-Control 的

> https://help.aliyun.com/document_detail/oss/api-reference/object/PutObject.html?spm=5176.docoss/api-reference/object/GetObject.6.185.Gh2wUm
> PUT一个Object的时候，OSS支持4个 HTTP RFC2616协议规定的Header 字段：Cache-Control、Expires、Content-Encoding、Content-Disposition。如果上传Object时设置了这些Header，则这个Object被下载时，相应的Header值会被自动设置成上传时的值。

Put 对象

`bucket.put_object('text.json', cache_control: "max-age:3600" ){|stream| stream << 'hello world.'}`

Get 对象返回的 Header 信息中并未包含相应的 Cache-Control 信息, 

```
HTTP/1.1 200 OK
Server: AliyunOSS
Date: Wed, 23 Dec 2015 02:00:53 GMT
Content-Type: application/json
Content-Length: 12
Connection: keep-alive
x-oss-request-id: 567A0055AD2D75FA0C84326C
Accept-Ranges: bytes
ETag: "3C4292AE95BE58E0C58E4E5511F09647"
Last-Modified: Wed, 23 Dec 2015 02:00:43 GMT
x-oss-object-type: Normal
```

**Comment by rockuw** [comment]
这个现在SDK没有支持，我今天加上吧。

**Comment by raecoo** [comment]
:+1: 最好 Cache-Control、Expires、Content-Encoding、Content-Disposition 都支持. 谢谢.

**Comment by rockuw** [comment]
你可以通过`:headers`指定自定义的header：

``` ruby
bucket.put_object(key, headers: {'cache-control' => 'maxage:3600'})
```
