### ISSUE TITLE
endpoint在README中写错了！

### ISSUE THREAD

**Issue by charlescui** [aliyun/aliyun-oss-ruby-sdk#2]
一处写的是：

```
oss-cn-hangzhou.aliyuncs.com
```

另外一处写的是：

```
oss-cn-hangzhou.oss.aliyuncs.com
```

多了一个.oss

这导致按照文档来写，永远都是签名错误！
而且endpoint列表的超链接点进去看不到endpoint。

**Comment by rockuw** [comment]
抱歉，节点列表在这里：http://help.aliyun.com/document_detail/oss/user_guide/endpoint_region.html
