### ISSUE TITLE
“Monkey patch to support #symbolize_keys!” is error!

### ISSUE THREAD

**Issue by zhyt1985** [aliyun/aliyun-oss-ruby-sdk#22]
Overwrite symbolize_keys method ( in '.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.4/lib/active_support/core_ext/hash/keys.rb') is error!
That makes some gem unable to work.

**Comment by rockuw** [comment]
Please help me reproduce this problem. It works fine in the rails demo: https://github.com/rockuw/oss-manager

**Comment by rockuw** [comment]
Released as 0.3.7
