### ISSUE TITLE
采用服务端签名后直传，可以多文件上传吗？

### ISSUE THREAD

**Issue by cloudsben** [aliyun/aliyun-oss-ruby-sdk#30]
![image](https://cloud.githubusercontent.com/assets/1283779/18027242/729679ce-6c91-11e6-89bd-142b74eee796.png)

**Comment by rockuw** [comment]
OSS目前不支持通过表单上传多个文件。https://help.aliyun.com/document_detail/31988.html

**Comment by cloudsben** [comment]
嗯，已经实现了采用服务端签名后多文件上传，另外还想问个问题，上传回调我看文档中是说需要公网的回调地址，这种情况该如何进行测试？

**Comment by rockuw** [comment]
你申请一个ECS，就有公网IP了，callback server可以参考：https://github.com/rockuw/oss-callback-server

**Comment by cloudsben** [comment]
我现在ECS，只是想知道如何对 callback server 进行调试

**Comment by rockuw** [comment]
https://github.com/aliyun/aliyun-oss-ruby-sdk/blob/master/README.md#%E4%B8%8A%E4%BC%A0%E5%9B%9E%E8%B0%83
