### ISSUE TITLE
断点下载错误：# Encoding::UndefinedConversionError: "\xE7" from ASCII-8BIT to UTF-8      

### ISSUE THREAD

**Issue by fenbaobao** [aliyun/aliyun-oss-ruby-sdk#34]
bucket.resumable_download(object_key, local_file)         

# Encoding::UndefinedConversionError: "\xE7" from ASCII-8BIT to UTF-8      

用直接下载则不会报错：
 bucket.get_object(object_key, :file => local_file)

**Comment by chen7897499** [comment]
我这边也是 但是只有在rails环境下才会这样 版本是4.2.4

**Comment by wetec** [comment]
我也遇到这个问题   应该是和rails有些地方冲突了，单纯的irb是可以执行的，但是require“rails”后就会出现这个编码问题。
![image](https://cloud.githubusercontent.com/assets/17491175/20050511/b83383c2-a504-11e6-9ed8-1ee915d34cf3.png)

**Comment by wetec** [comment]
require“rails”  后就会出现这样的问题  
![image](https://cloud.githubusercontent.com/assets/17491175/20050544/df29c4d2-a504-11e6-9a32-42e6afe4469e.png)

**Comment by rockuw** [comment]
多谢反馈，我看一下。

**Comment by rockuw** [comment]
稍后会发出0.5.0版本。

**Comment by rockuw** [comment]
v0.5.0
