### ISSUE TITLE
rest-client error

### ISSUE THREAD

**Issue by oksep** [aliyun/aliyun-oss-ruby-sdk#39]
What about this?
A very simple example
```
require 'aliyun/oss'
client = Aliyun::OSS::Client.new(
  :endpoint => 'xxx',
  :access_key_id => 'xxx',
  :access_key_secret => 'xxx',
  :cname => false)
bucket = client.get_bucket('server-logs')
objects = bucket.list_objects
objects.each{ |o| puts o.key }
```

Getting error:
`/Users/septenary/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in 'fetch': key not found: :ciphers (KeyError)`

**Comment by baiyubin** [comment]
please upgrade rest-client-1.8.0 to 2.0.

**Comment by oksep** [comment]
@baiyubin  我通过 gem update 升级到 rest-client-2.0.0 运行仍然报同样的错误，我把 rest-client-1.8.0 卸载了，重新运行，提示 sdk 依赖的 1.8.0 找不到

**Comment by oksep** [comment]
rest-client 2.0 对 openssl 做了兼容，但 sdk  依赖 rest-client 1.8.0 ，所以我将 rest-client 1.8.0 的源码 request.rb 注解掉了部分代码，这样能跑通，但始终不是好的解决方案
```
      # unless @ssl_opts.include?(:ciphers)
      #   # If we're on a Ruby version that has insecure default ciphers,
      #   # override it with our default list.
      #   if WeakDefaultCiphers.include?(
      #        OpenSSL::SSL::SSLContext::DEFAULT_PARAMS.fetch(:ciphers))
      #     @ssl_opts[:ciphers] = DefaultCiphers
      #   end
      # end
```

**Comment by rockuw** [comment]
可能是ruby 2.4.0的问题，你换用其他版本试一下。

**Comment by rockuw** [comment]
Fixed @0.6.0
