### ISSUE TITLE
升级rest-client到2.0.x

### ISSUE THREAD

**Issue by pingguoilove** [aliyun/aliyun-oss-ruby-sdk#45]
持续集成平台通过fastlane打包，然后将包传到oss，但fastlane升级后，依赖了mime-types 3.0版本，而aliyun-sdk以来的rest-client 1.8.0所依赖的mime-types需要小于3.0。建议将rest-client升级到2.0.x，目前最新版。

**Comment by Xuhao** [comment]
实作在 #46 . 可以关掉吗？

**Comment by pingguoilove** [comment]
@Xuhao 我试试

**Comment by rockuw** [comment]
Fixed @0.6.0
