### ISSUE TITLE
nokogiri版本能否提升最新的1.7.2

### ISSUE THREAD

**Issue by railsfans** [aliyun/aliyun-oss-ruby-sdk#52]
我用最新的rails5.1.2
In snapshot (Gemfile.lock):
    nokogiri (= 1.7.2)
aliyun-sdk was resolved to 0.5.0, which depends on
      nokogiri (< 1.7.0, ~> 1.6)

**Comment by railsfans** [comment]
我直接把aliyun-sdk.gemspec里的nokogiri版本升级到1.7.2，然后打包自己用了，调用上传文件api还是出现如下错误
aliyun-sdk-0.5.0/lib/aliyun/oss/http.rb:128:in `read': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
        from /home/yxx/.rvm/gems/ruby-2.4.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:56:in `read'
但是我看到有个分支的提交已经将gemspec提高到rest-client-2.0.2了，还是有bug，希望能解决下。

**Comment by ouabing** [comment]
同求

**Comment by li-thy-um** [comment]
同求

不知道为何要限制 nokogiri 的版本

现在  nokogiri 应该已经 1.8 了

**Comment by luluhongxu** [comment]
@railsfans ， 您好！
我先后用的 nokogiri 1.7.2 版本和nokogiri  1.8.1 版本，aliyun-sdk为`0.6.0`版本， 没有发现你说的这个问题， 你试试看看。 如果有问题， 把你的调用的源代码发上来看一下。

**Comment by ken-zy** [comment]
GitHub 会有警告 ⚠️
非常影响用户体验，建议不要对 nokogiri 进行版本限制。
![snip20180605_2](https://user-images.githubusercontent.com/14258352/40952224-f773ce12-68ac-11e8-8421-f3ae0f7a730c.png)
![snip20180605_3](https://user-images.githubusercontent.com/14258352/40952225-fac02732-68ac-11e8-9bec-fc2f7facb81b.png)

**Comment by rockuw** [comment]
Sorry for the late update. Please use 0.7.0 . Thanks for the feedback!

**Comment by ken-zy** [comment]
But the latest version is 0.6.0 
How can I install the 0.7.0
