### ISSUE TITLE
如何修改默认的 log file ？

### ISSUE THREAD

**Issue by li-thy-um** [aliyun/aliyun-oss-ruby-sdk#56]
`Aliyun::Common::Logging.set_log_file 
`
这个操作不起作用

尝试调整 https://github.com/TapasTech/aliyun-oss-ruby-sdk/blob/master/lib/aliyun/common/logging.rb

```ruby
      # 设置日志输出的文件
      def self.set_log_file(file)
        @log_file = file
        
        level = Logging.logger.level
        @logger = nil
        Logging.logger.level = level

        @log_file
      end
```

**Comment by luluhongxu** [comment]
@li-thy-um , 你好！ 你要在 所有logger操作之前 调用set_log_file设置log文件， 这样才起作用。 你说的不起作用，是由于已经用默认的文件打印过一些日志了， 然后中途 再改变日志文件路径， 这样肯定不起作用， 这样的用法不符合正常习惯，因为中间过程改变日志文件路径 会导致日志打印 存放到多个不同的地方。
