### ISSUE TITLE
does the lib support STS token generation?

### ISSUE THREAD

**Issue by dfguo** [aliyun/aliyun-oss-ruby-sdk#7]
Does the lib support STS token generation? Thanks!

**Comment by rockuw** [comment]
The next version of aliyun-sdk(0.2.0) with **full support** for STS, will be released today. 
Thanks.

**Comment by dfguo** [comment]
nice, that was on time. By the way, where can I find docs related to STS? Couldn't find it here: http://doc.oss.aliyuncs.com/

**Comment by rockuw** [comment]
STS: https://help.aliyun.com/document_detail/ram/intro/concepts.html
OSS using STS: https://help.aliyun.com/document_detail/oss/api-reference/access-control/granting-permissions.html

**Comment by rockuw** [comment]
try `gem install aliyun-sdk` now.

Fixed by #8

**Comment by rockuw** [comment]
Refer to https://github.com/aliyun/aliyun-oss-ruby-sdk#使用sts创建client for an example
